#!/bin/bash

##Download jdk
wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
tar xf jdk*

##Download TomCat
wget http://apache.cp.if.ua/tomcat/tomcat-8/v8.0.53/bin/apache-tomcat-8.0.53.tar.gz
tar xf apache-tomcat*

##Download Maven
wget http://apache.ip-connect.vn.ua/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
tar xf apache-maven*

rm -rf *.tar.gz

mv jdk* java8
mv apache-maven* maven
mv apache-tomcat* tomcat8

echo 'JAVA_HOME=/src/java8' >> /root/.bashrc
echo 'export JAVA_HOME' >> /root/.bashrc
echo 'PATH=$PATH:$JAVA_HOME' >> /root/.bashrc
source /root/.bashrc

git clone https://github.com/efsavage/hello-world-war.git
cd /src/hello-world-war
/src/maven/bin/mvn package


rm -rf /src/tomcat8/webapps/*
cp /src/setenv.sh /src/tomcat8/bin/setenv.sh
cp /src/hello-world-war/target/hello-world-war-1.0.0.war /src/tomcat8/webapps/hello.war
/src/tomcat8/bin/startup.sh
